Wed May 27 19:35:59 CEST 2015 Thread[79,5,JADE User Agents] Cleanup action starting
java.sql.SQLException: Database 'synthetic' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at aml.entity.SynthDB.getDBConnection(SynthDB.java:68)
	at aml.entity.SynthDB.insertRecordIntoTable(SynthDB.java:44)
	at aml.agent.Receiver.action(Receiver.java:44)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.behaviours.CompositeBehaviour.action(CompositeBehaviour.java:109)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1552)
	at jade.core.Agent.run(Agent.java:1491)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Database 'synthetic' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 23 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'synthetic' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at aml.entity.SynthDB.getDBConnection(SynthDB.java:68)
	at aml.entity.SynthDB.insertRecordIntoTable(SynthDB.java:44)
	at aml.agent.Receiver.action(Receiver.java:44)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.behaviours.CompositeBehaviour.action(CompositeBehaviour.java:109)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1552)
	at jade.core.Agent.run(Agent.java:1491)
	at java.lang.Thread.run(Thread.java:745)
============= end nested exception, level (1) ===========
Cleanup action completed
